-- create table mybag(
--     Color varchar(30),
--     Compartment int,
--     Capacity varchar(30),
--     constraint pk_mybage
--     primary key (Color,Compartment,Capacity)
-- );
-- -- color = Red , Green ,Blue
-- -- Compartment = 4,5,6
-- -- Capacity = 25L,30L,35L;
-- insert into mybag values("R",4,"25L"); 
-- insert into mybag values("G",4,"25L"); 
-- insert into mybag values("B",4,"25L"); 

-- select * from mybag;